export const emptyTodayKeyword = {
  id: 0,
  datetime: '',
  keyword1: '',
  keyword2: '',
  keyword3: '',
  keyword4: '',
  keyword5: '',
  keyword6: '',
  keyword7: '',
  keyword8: '',
  keyword9: '',
  keyword10: '',
  value1: 0,
  value2: 0,
  value3: 0,
  value4: 0,
  value5: 0,
  value6: 0,
  value7: 0,
  value8: 0,
  value9: 0,
  value10: 0,
  stocks: '',
  createdAt: '',
  updatedAt: '',
};
